/**
 * Type definitions for the Siderust Lab "latest" exported artifacts.
 *
 * Source of truth: the JSON files generated by the lab pipeline and copied
 * into `benches/latest_results/` (`scorecard.json`, `manifest.json`,
 * `experiments/<id>.json`). Every field mirrors what the export emits today.
 */

export type RowStatus = 'ok' | 'skipped' | 'failed' | string;

export interface ScorecardMetric {
  key: string;
  label: string;
  unit: string;
}

export interface ScorecardRow {
  library: string;
  display_name: string;
  profile: string | null;
  rankable_accuracy: boolean;
  rank_exclusion_reason: string | null;
  candidate_parity: string | null;
  comparability_class: string | null;
  model_parity_class: string | null;
  selected_model: string | null;
  model_source: string | null;
  lane: string | null;
  status: RowStatus;
  skip_reason: string | null;
  failure_reason: string | null;
  p50: number | null;
  p99: number | null;
  max: number | null;
  rms: number | null;
  mean: number | null;
  ns_per_op: number | null;
  scalar_warm_ns_per_op: number | null;
  scalar_warm_cv: number | null;
  batch_throughput_ns_per_op: number | null;
  batch_throughput_items_per_sec: number | null;
  setup_ms: number | null;
  setup_measured: boolean | null;
  performance?: {
    scalar_warm: { ns_per_op: number; cv: number; rounds: number; n_per_round: number; valid: boolean; warnings: string[] } | null;
    batch_throughput: unknown | null;
    setup_metrics: unknown | null;
  };
  perf_valid: boolean;
  perf_cv_pct: number | null;
  perf_warnings: string[];
  source_provenance?: { source?: string; adapter?: string; model?: string };
  reference_source_tag: string | null;
  accuracy_delta_vs_best: number | null;
  performance_delta_vs_best_pct: number | null;
}

export interface ScorecardExperiment {
  experiment: string;
  title: string;
  reference_library: string;
  reference_model: string | null;
  reference_lane: string | null;
  tier: string;
  metric: ScorecardMetric;
  rows: ScorecardRow[];
  best_accuracy: string | null;
  best_accuracy_exact: string | null;
  best_performance: string | null;
}

export interface ScorecardFamily {
  family: string;
  experiments: ScorecardExperiment[];
}

export interface Scorecard {
  run_id: string;
  timestamp: string;
  machine: string;
  git_shas: Record<string, string>;
  references: string[];
  families: ScorecardFamily[];
}

export interface ManifestConfig {
  experiments: string[];
  n: number;
  seed: number;
  perf_enabled: boolean;
  perf_rounds: number;
  ci_mode: boolean;
  adapters: string[];
  siderust_profiles: string[];
  horizons_use_cache: boolean;
  horizons_allow_network: boolean;
}

export interface ManifestMetadata {
  date: string;
  git_shas: Record<string, string>;
  git_branch: string;
  cpu: string;
  cpu_count: number;
  os: string;
  platform_detail: string;
  toolchain: Record<string, string>;
  cpu_model: string;
  adapter_binaries?: Record<string, unknown>;
}

export interface ManifestExcludedCandidate {
  candidate_id: string;
  support_status: string;
  reason: string;
}

export interface ManifestPerExperimentEntry {
  completed?: boolean;
  excluded_candidates?: ManifestExcludedCandidate[];
}

export interface ManifestCompleteness {
  requested: number;
  completed: number;
  missing: string[];
  completed_experiments: string[];
  libraries: string[];
  per_experiment?: Record<string, ManifestPerExperimentEntry>;
}

export interface Manifest {
  run_id: string;
  config: ManifestConfig;
  metadata: ManifestMetadata;
  completeness: ManifestCompleteness;
  experiment_count: number;
  total_results: number;
}

export interface ExperimentDescription {
  title?: string;
  what?: string;
  why?: string;
  units?: string;
  interpret?: string;
  performance_contract?: string;
}

export interface ExperimentRowDetail {
  candidate_library: string;
  candidate_profile: string | null;
  description?: ExperimentDescription;
  alignment?: Record<string, unknown> & { note?: string; models?: Record<string, string> };
  status: RowStatus;
}

export interface ExperimentDetail {
  experiment: string;
  run_id: string;
  rows: ExperimentRowDetail[];
}

export interface LabBundle {
  scorecard: Scorecard;
  manifest: Manifest;
  experiments: Record<string, ExperimentDetail | null>;
}
